apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: elasticsearch-config
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |-
    cluster.name: elasticsearch
    node.name: elasticsearch-data
    discovery.type: single-node
    network.host: 0.0.0.0
    xpack.security.enabled: false
    xpack.security.transport.ssl.enabled: true
    xpack.monitoring.collection.enabled: true