apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  version: 8.1.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
